### PR TITLE
Feature complex conditions

### PR DESCRIPTION
**Pull request by poison**
Big rework in condition parsing, but preserves backwards compatibility.
With this patch, IF contexts can have multiple and complex conditions. Eg.: {{IF ((a == "1" || a == "2") && b == "3")}}

In order to do this, the RPN http://en.wikipedia.org/wiki/Reverse_Polish_notation is used (using the Shunting-yard algorithm http://en.wikipedia.org/wiki/Shunting-yard_algorithm). This is a parenthesis free representation of the expression, so easier to evaluate.

Please have a look at it, I added a couple of tests, and cleaned up some older methods. Any comments are greatly appreciated.

Best,
Nicolas

### CODE REVIEW

**Comment by alexeyrybak** [comment]
This is great and dangerous ;) Joking. Do you have anything else in the patch queue? I have several fixes which I'd like to release separately, and apply your changes after (as they potentially may break a lot). If you have anything else - please pull, maybe it will be better release all your changes all together.

**Comment by poison** [comment]
Hi Alexey,

I have no other patches. I know my coworker Maurus has https://github.com/alexeyrybak/blitz/pull/13. Good idea to release this patch separately.

Best,
Nicolas

**Comment by alexeyrybak** [comment]
OK, I just released 0.8.15 with all other changes and plan to review and release your patch as 0.8.16 during next days. Thanks.

**Comment by WouterDS** [comment]
Can't wait, really looking forward to 0.8.16!

**Comment by alexeyrybak** [comment]
Merged with some changes (conflicts with Tony's memleak patches). Didn't test intensively yet, and didn't release the tarball, but all the tests passed ;)

**Pull request merged**
