### PR TITLE
Use *_ex() API to preserve input variables

### PR DESCRIPTION
**Pull request by mikhainin**
The same problem that we observed in #74

Additionally, fixed a couple of problems when `BLITZ_DEBUG` is on

### CODE REVIEW

**Comment by alexeyrybak** [comment]
is there any way to split this pull into two: first _ex change, second adding new debug functions and changing whole bunch of debug code? they both seem to be OK just for the sake of quick and granular revoke if something goes wrong.

**Comment by mikhainin** [comment]
yes, ofc.

**Comment by mikhainin** [comment]
I extracted the debug stuff in #78. 
Let's proceed with that one and then I will update this PR. 

This change depends on `blitz_dump_ht()` which is added there. I know, it's a bit messy now...

**Comment by alexeyrybak** [comment]
this merge still has debug stuff?

**Comment by mikhainin** [comment]
Force-pushed the branch. No more debug stuff :)

**Pull request merged**
