### PR TITLE
Link to Wiki from homepage.

### PR DESCRIPTION
**Pull request by burtyish**
Fixes alexeyrybak/blitz#55

### CODE REVIEW

**Comment by alexeyrybak** [comment]
why do you delete all the content?

**Comment by burtyish** [comment]
I saw that the installation section was a copy of https://github.com/alexeyrybak/blitz/wiki/Installation so I thought this would avoid duplication. Also, it the README was outdated.
If you'd like to keep the existing README content, I'd be happy to format it nicely in markdown and just add a link to the Wiki at the top. 
@alexeyrybak, What do you think?

**Comment by alexeyrybak** [comment]
REDAME is often used by old-school guys so can you please just add a link if you like, but keep all the existing text in there? Thanks.

**Comment by alexeyrybak** [comment]
cook thanks
if something in the text is outdated - feel free to fix

**Pull request merged**
