### PR TITLE
Feature include scope

### PR DESCRIPTION
**Pull request by poison**
This feature adds the ability to pass some scope to an include() call.
Normally, include() resets it's internal scope, so inside the included template, the $_top and the $_parent variables don't make any sense (since it's the same as $_ variable). But if you want to make something specific available inside the include()d template you can use the following syntax:

include('filename.tpl', user=$_top.user, var2="my var")

Inside the 'filename.tpl' you can now refer to the $user and $var2 variables.

Best,
Nicolas

### CODE REVIEW

**Comment by WouterDS** [comment]
🎉🎉🎉

**Comment by alexeyrybak** [comment]
OK, so here is a follow-up. Yura's patches (https://github.com/alexeyrybak/blitz/pull/37 and https://github.com/alexeyrybak/blitz/pull/38) were important for Badoo so I merged that first, and we got these conflicts. So we need to resolve the conflict, and I hope Yura finds time to do this soon.

**Comment by YuriyNasretdinov** [comment]
File tests/include-scope-inner.tpl is missing

**Comment by alexeyrybak** [comment]
closing, as this was fixed in #40, this brach had conflicts.

**Pull request closed without merging**
