### PR TITLE
Feature native if

### PR DESCRIPTION
**Pull request by poison**
Reworked the IF evaluation to use php's native compare_function. Also cleaned up the code and fixed some bugs. More verbose error messages if something's wrong with IF's (issue-27) and fixed a huge bug with OR (||) in an IF statement (+ added tests).

Please let me know what you think.

### CODE REVIEW

**Comment by alexeyrybak** [comment]
Thanks a lot for the patch, but it will take some time to review. 
My current concern is only the difference between old one-block if/unless and this new logic which lives only for the contexts, so the behaviour is ambiguous.

**Comment by poison** [comment]
Yes, I anticipated this, I'm working on adding the support to the if()/unless() function calls as well, but it takes a little longer, and right now there are some critical bugs in the current stable version (eg. or functionality doesn't work)

**Comment by alexeyrybak** [comment]
OK. Could you please clarify, what bugs? Added by this patch, or added by previous patches? Are they in the github tracker?

**Comment by poison** [comment]
In 0.8.18 there's an issue with OR (see issue #30). Currently fails. This rework basically fixes it. It's in there since the beginning of complex conditions feature, when 1 operator was not set or defined.

**Comment by poison** [comment]
Alexey, I added what you requested: a3987274aa6ecbb4bbaa649af4070e532ed9b3ef adds complex if support to the if() and unless() functions

**Comment by alexeyrybak** [comment]
Oh great! Let's merge and see the performance...

**Comment by poison** [comment]
Performance should be the same, my memory profiler also didn't find any regression issues (although there are some warnings that valgrind shows on other tests, wrt the scopes, I still need to look into this).

Do you have any performance benchmark suites to check performance? If so I'd be interested in knowing how to run/reproduce it.

Best,
Nicolas

**Comment by alexeyrybak** [comment]
There's more or less complex template here http://alexeyrybak.com/blitz/lebowski.html and several methods to parse here http://alexeyrybak.com/blitz/lebowski_bench.tar.gz. I don't expect any change on these tests though.

**Comment by poison** [comment]
Okay, looking forward to the release of 0.8.19 then ;)

**Comment by poison** [comment]
Alexey,

Do you have any objections to release 0.8.19 with the current code in master? It will help me to enforce this version in homebrew and compile server packages (otherwise I need to create internally a version 0.8.18.1 which is not the same as upstream).

Best,
Nicolas

**Comment by alexeyrybak** [comment]
No, I just didn't have time to switch to this, review, update CHANGES and release. Give me a couple of days, please. I also don't understand some github visualisations so I want to check that important Tony's patchesn were not lost + this new __construct issue #31 .

**Comment by alexeyrybak** [comment]
Cool, so it's 0.9.1 now. Thanks a lot!

**Pull request merged**
